druid:
  datasource:
    name: mydatabases    
    #url: jdbc:sqlserver://192.168.170.65:1433;databasename=phfund_user
    #username: GY_softweb_1109
    #password: pw_2BFDSLFLKFLSDFF    
    url: jdbc:sqlserver://192.168.3.45:1433;databasename=phfund_user_1
    username: jzq123456
    password: jzq123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    filters: stat,wall,log4j
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: false
    maxOpenPreparedStatements: 20
#auth:
#  datasource:
#    name: mydatabases
#    url: jdbc:sqlserver://192.168.3.45:1433;databasename=dg_auth
#    username: admin
#    password: admin
#    type: com.alibaba.druid.pool.DruidDataSource
#    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
#    filters: stat,wall,log4j
#    maxActive: 20
#    initialSize: 1
#    maxWait: 60000
#    minIdle: 1
#    timeBetweenEvictionRunsMillis: 60000
#    minEvictableIdleTimeMillis: 300000
#    validationQuery: SELECT 1
#    testWhileIdle: true
#    testOnBorrow: false
#    testOnReturn: false
#    poolPreparedStatements: false  #如果是oracle 则可以设置为true  如果是mysql则设置false 分库分表较多的数据库，建议配置为false。
#    maxOpenPreparedStatements: 20
server:
  port: 8026
  jsp-servlet:
    init-parameters:
      development: true
spring:
  resources:
    static-locations: classpath:/
  mvc:
    view:
      suffix: .jsp
      prefix: /WEB-INF/jsp/
    static-path-pattern: /**
    favicon:
      enabled: false
  thymeleaf:
      cache: false
      enabled: false
  data:
    rest:
      base-path: /app
#redis
  redis:
      host: 193.112.94.95
      port: 6379
      # 连接超时时间（毫秒）
      timeout: 300
      pool:
        #连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
         # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 1
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.jcl.gycms.entity
mapper:
  mappers:
     - com.jcl.gycms.tkMapper.TkMapper
  identity: SQLSERVER

pagehelper:
  helper-dialect: sqlserver
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
security:
  basic:
    enabled: false

gycms :
  imgUrl: C:\soft\apache2\htdocs\images\
  showUrl: http://127.0.0.1/images/
  qxIndex: 6
  username: admin
  password: 654321